#!/usr/bin/python
# -*- coding: utf-8 -*-

TYPE_S = 0
TYPE_F = 1
TYPE_M = 2
TYPE_FM = 3

GENERAL_CALENDAR = [
    (1, 1, u"Maria SS. Madre di Dio", TYPE_S),
    (1, 2, u"Ss. Basilio Magno e Gregorio Nazianzeno, vescovi e dottori della Chiesa", TYPE_M),
    (1, 6, u"Epifania del Signore", TYPE_S),
    (1, 7, u"S. Raimondo da Peñafort", TYPE_FM),
    (1, 13, u"S. Ilario, vescovo e dottore della Chiesa", TYPE_FM),
    (1, 17, u"S. Antonio, abate", TYPE_M),
    (1, 20, u"S. Fabiano, papa e martire", TYPE_FM),
    (1, 20, u"S. Sebastiano, martire", TYPE_FM),
    (1, 21, u"S. Agnese, vergine e martire", TYPE_M),
    (1, 22, u"S. Vincenzo, diacono e martire", TYPE_FM),
    (1, 24, u"S. Francesco di Sales, vescovo e dottore della Chiesa", TYPE_M),
    (1, 25, u"Conversione di S. Paolo, apostolo", TYPE_F),
    (1, 26, u"Ss. Timòteo e Tito, vescovi", TYPE_M),
    (1, 27, u"S. Angela Merici, vergine", TYPE_FM),
    (1, 28, u"S. Tommaso d'Aquino, sacerdote e dottore della Chiesa", TYPE_M),
    (1, 31, u"S. Giovanni Bosco, sacerdote", TYPE_M),

    (2, 2, u"Presentazione del Signore", TYPE_F),
    (2, 3, u"S. Biagio, vescovo e martire", TYPE_FM),
    (2, 4, u"S. Ansgario (Oscar), vescovo", TYPE_FM),
    (2, 5, u"S. Agata, vergine e martire", TYPE_M),
    (2, 6, u"Ss. Paolo Miki e compagni, martiri", TYPE_M),
    (2, 8, u"S. Girolamo Emiliani", TYPE_FM),
    (2, 8, u"S. Giuseppina Bakhita, vergine", TYPE_FM),
    (2, 10, u"S. Scolastica, vergine", TYPE_M),
    (2, 11, u"Beata Vergine Maria di Lourdes", TYPE_FM),
    (2, 14, u"Ss. Cirillo, monaco, e Metodio, vescovo, patroni d'Europa", TYPE_F),
    (2, 17, u"Ss. Sette Fondatori dell'Ordine dei Servi della beata Vergine Maria", TYPE_FM),
    (2, 21, u"S. Pier Damiani, vescovo e dottore della Chiesa", TYPE_FM),
    (2, 22, u"Cattedra di S. Pietro, apostolo", TYPE_F),
    (2, 23, u"S. Policarpo, vescovo e martire", TYPE_M),

    (3, 4, u"S. Casimiro", TYPE_FM),
    (3, 7, u"Ss. Perpetua e Felicita, martiri", TYPE_M),
    (3, 8, u"S. Giovanni di Dio, religioso", TYPE_FM),
    (3, 9, u"S. Francesca Romana, religiosa", TYPE_FM),
    (3, 17, u"S. Patrizio, vescovo", TYPE_FM),
    (3, 18, u"S. Cirillo di Gerusalemme, vescovo e dottore della Chiesa", TYPE_FM),
    (3, 19, u"S. Giuseppe, sposo della beata Vergine Maria", TYPE_S),
    (3, 23, u"S. Turibio de Mongrovejo, vescovo", TYPE_FM),
    (3, 25, u"Annunciazione del Signore", TYPE_S),

    (4, 2, u"S. Francesco de Paola, eremita", TYPE_FM),
    (4, 4, u"S. Isidoro, vescovo e dottore della Chiesa", TYPE_FM),
    (4, 5, u"S. Vincenzo Ferrer, sacerdone", TYPE_FM),
    (4, 7, u"S. Giovanni Battista de la Salle, sacerdote", TYPE_M),
    (4, 11, u"S. Stanislao, vescovo e martire", TYPE_M),
    (4, 13, u"S. Martino I, papa e martire", TYPE_FM),
    (4, 21, u"S. Anselmo, vescovo e dottore della Chiesa", TYPE_FM),
    (4, 23, u"S. Adalberto, vescovo e martire", TYPE_FM),
    (4, 23, u"S. Giorgio, martire", TYPE_FM),
    (4, 24, u"S. Fedele da Sigmaringen, sacerdote e martire", TYPE_FM),
    (4, 25, u"S. Marco, evangelista", TYPE_F),
    (4, 28, u"S. Luigi Maria da Montfort, sacerdote", TYPE_FM),
    (4, 28, u"S. Pietro Chanel, sacerdote e martire", TYPE_FM),
    (4, 29, u"S. Caterina da Siena, vergine e dottore della Chiesa, patrona d'Italia e d'Europa", TYPE_F),
    (4, 30, u"S. Pio V, papa", TYPE_FM),

    (5, 1, u"S. Giuseppe Lavoratore", TYPE_FM),
    (5, 2, u"S. Atanasio, vescovo e dottore della Chiesa", TYPE_M),
    (5, 3, u"Ss. Filippo e Giacomo, apostoli", TYPE_F),
    (5, 12, u"Ss. Nereo e Achilleo, martiri", TYPE_FM),
    (5, 12, u"S. Pancrazio, martire", TYPE_FM),
    (5, 13, u"Beata Vergine Maria di Fatima", TYPE_FM),
    (5, 14, u"S. Mattia, apostolo", TYPE_F),
    (5, 18, u"S. Giovanni I, papa e martire", TYPE_FM),
    (5, 20, u"S. Bernardino da Siena, sacerdote", TYPE_FM),
    (5, 21, u"Ss. Cristoforo Magellanes, sacerdote, e compagni, martiri", TYPE_FM),
    (5, 22, u"S. Rita da Cascia, religiosa", TYPE_FM),
    (5, 25, u"S. Beda Venerabile, sacerdote e dottore della Chiesa", TYPE_FM),
    (5, 25, u"S. Gregorio VII, papa", TYPE_FM),
    (5, 25, u"S. Maria Maddalena de' Pazzi, vergine", TYPE_FM),
    (5, 26, u"S. Filippo Neri, sacerdoti", TYPE_M),
    (5, 27, u"S. Agostino di Canterbury, vescovo", TYPE_FM),
    (5, 31, u"Visitazione della Beata Vergine Maria", TYPE_F),

    (6, 1, u"S. Giustino, martire", TYPE_M),
    (6, 2, u"Ss. Marcellino e Pietro, martiri", TYPE_FM),
    (6, 3, u"S. Carlo Lwanga e compagni, martiri", TYPE_M),
    (6, 5, u"S. Bonifacio, vescovo e martire", TYPE_M),
    (6, 6, u"S. Norberto, vescovo", TYPE_FM),
    (6, 9, u"S. Efrem, diacono e dottore della Chiesa", TYPE_FM),
    (6, 11, u"S. Barnaba, apostolo", TYPE_M),
    (6, 13, u"S. Antonio da Padova, sacerdote e dottore della Chiesa", TYPE_M),
    (6, 19, u"S. Romualdo, abate", TYPE_FM),
    (6, 21, u"S. Luigi Gonzaga, religioso", TYPE_M),
    (6, 22, u"S. Paolino da Nola, vescovo", TYPE_FM),
    (6, 22, u"Ss. Giovanni Fisher, vescovo, e Tommaso More, martiri", TYPE_FM),
    (6, 24, u"Natività di S. Giovanni Battista", TYPE_S),
    (6, 27, u"S. Cirillo d'Alessandria, vescovo e dottore della Chiesa", TYPE_FM),
    (6, 28, u"S. Ireneo, vescovo e martire", TYPE_M),
    (6, 29, u"Ss. Pietro e Paolo, apostoli", TYPE_S),
    (6, 30, u"Ss. Primi martiri della Chiesa di Roma", TYPE_FM),

    (7, 3, u"S. Tommaso, apostolo", TYPE_F),
    (7, 4, u"S. Elisabetta di Portogallo", TYPE_FM),
    (7, 5, u"S. Antonio Maria Zaccaria, sacerdote", TYPE_FM),
    (7, 6, u"S. Maria Goretti, vergine e martire", TYPE_FM),
    (7, 9, u"Ss. Agostino Zhao Rong, sacerdote, e compagni, martiri", TYPE_FM),
    (7, 11, u"S. Benedetto, abate, patrono d'Europa", TYPE_F),
    (7, 13, u"S. Enrico", TYPE_FM),
    (7, 14, u"S. Camillo de Lellis, sacerdote", TYPE_FM),
    (7, 15, u"S. Bonaventura, vescovo e dottore della Chiesa", TYPE_M),
    (7, 16, u"Beata Vergine Maria del Monte Carmelo", TYPE_FM),
    (7, 20, u"S. Apollinare, vescovo e martire", TYPE_FM),
    (7, 21, u"S. Lorenzo da Brindisi, sacerdote e dottore della Chiesa", TYPE_FM),
    (7, 22, u"S. Maria Maddalena", TYPE_M),
    (7, 23, u"S. Brigida, religiosa", TYPE_F),
    (7, 24, u"S. Charbel Makhluf, sacerdote", TYPE_FM),
    (7, 25, u"S. Giacomo, apostolo", TYPE_F),
    (7, 26, u"S. Gioacchino e Anna, genitori della Beata Vergine Maria", TYPE_M),
    (7, 29, u"S. Marta", TYPE_M),
    (7, 30, u"S. Pietro Crisologo, vescovo e dottore della Chiesa", TYPE_FM),
    (7, 31, u"S. Ignazio di Loyola, sacerdote", TYPE_M),

    (8, 1, u"S. Alfonso Maria de' Liguori, vescovo e dottore della Chiesa", TYPE_M),
    (8, 2, u"S. Eusebio di Vercelli, vescovo", TYPE_FM),
    (8, 2, u"S. Pier Giuliano Eymard, sacerdote", TYPE_FM),
    (8, 4, u"S. Giovanni Maria Vianney, sacertode", TYPE_M),
    (8, 5, u"Dedicazione della Basilica di S. Maria Maggiore", TYPE_FM),
    (8, 6, u"Trasfigurazione del Signore", TYPE_F),
    (8, 7, u"Ss. Sisto II, papa, e compagni, martiri", TYPE_FM),
    (8, 7, u"S. Gaetano, sacerdote", TYPE_FM),
    (8, 8, u"S. Domenico, sacerdote", TYPE_M),
    (8, 9, u"S. Teresa Benedetta della Croce, vergine e martire, patrona d'Europa", TYPE_F),
    (8, 10, u"S. Lorenzo, diacono e martire", TYPE_F),
    (8, 11, u"S. Chiara, vergine", TYPE_M),
    (8, 12, u"S. Giovanna Francesca de Chantal, religiosa", TYPE_FM),
    (8, 13, u"Ss. Ponziano, papa, e Ippolito, sacerdote, martiri", TYPE_FM),
    (8, 14, u"S. Massimiliano Maria Kolbe, sacerdote e martire", TYPE_M),
    (8, 15, u"Assunzione della beata Vergine Maria", TYPE_S),
    (8, 16, u"S. Stefano di Ungheria", TYPE_FM),
    (8, 19, u"S. Giovanni Eudes, sacerdote", TYPE_FM),
    (8, 20, u"S. Bernardo, abate e dottore della Chiesa", TYPE_M),
    (8, 21, u"S. Pio X, papa", TYPE_M),
    (8, 22, u"Beata Vergine Maria Regina", TYPE_M),
    (8, 23, u"S. Rosa da Lima, vergine", TYPE_FM),
    (8, 24, u"S. Bartolomeo, apostolo", TYPE_F),
    (8, 25, u"S. Ludovico", TYPE_FM),
    (8, 25, u"S. Giuseppe Calasanzio, sacerdote", TYPE_FM),
    (8, 27, u"S. Monica", TYPE_M),
    (8, 28, u"S. Agostino, vescovo e dottore della Chiesa", TYPE_M),
    (8, 29, u"Martirio di S. Giovanni Battista", TYPE_M),

    (9, 3, u"S. Gregorio Magno, papa e dottore della Chiesa", TYPE_M),
    (9, 8, u"Natività della beata Vergine Maria", TYPE_F),
    (9, 9, u"S. Pietro Claver, sacerdote", TYPE_FM),
    (9, 12, u"SS. Nome di Maria", TYPE_FM),
    (9, 13, u"S. Giovanni Crisostomo, vescovo e dottore della Chiesa", TYPE_M),
    (9, 14, u"Esaltazione della Santa Croce", TYPE_F),
    (9, 15, u"Beata Vergine Maria Addolorata", TYPE_M),
    (9, 16, u"Ss. Cornelio, papa, e Cipriano, vescovo, martiri", TYPE_M),
    (9, 17, u"S. Roberto Bellarmino, vescovo e dottore della Chiesa", TYPE_FM),
    (9, 19, u"S. Gennaro, vescovo e martire", TYPE_FM),
    (9, 20, u"Ss. Andrea Kim Taegon, sacerdote, Paolo Chong Hasang e compagni, martiri", TYPE_M),
    (9, 21, u"S. Matteo, apostolo ed evangelista", TYPE_F),
    (9, 23, u"S. Pio da Pietralcina, sacerdote", TYPE_M),
    (9, 26, u"Ss. Cosma e Damiano, martiri", TYPE_FM),
    (9, 27, u"S. Vincenzo de' Paoli, sacerdote", TYPE_M),
    (9, 28, u"S. Venceslao, martire", TYPE_FM),
    (9, 28, u"S. Lorenzo Ruiz e compagni, martiri", TYPE_FM),
    (9, 29, u"Ss. Michele, Gabriele e Raffaele, arcangeli", TYPE_F),
    (9, 30, u"S. Girolamo, sacerdote e dottore della Chiesa", TYPE_M),
]
